version: '3.1'

services:
  db:
    image: mysql:5.6
    container_name: mysql-container
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: blog
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    image: eldron/spring-blog:0.2
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet

networks:
  webnet:
