version: "3.1"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: basket
      MYSQL_USER: basket_user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'