version: "3.0"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: basket
      MYSQL_USER: basketDB
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'